[package]
name = "dns-blackbox"
version = "0.1.0"
edition = "2021"
authors = ["Q Misell <q@as207960.net>"]

[dependencies]
rocket = { version = "=0.5.0-rc.3", features = [] }
trust-dns-client = "*"
tokio = { version = "1", features = [] }
rand = "0.8.5"
pretty_env_logger = "0.5.0"
