# Generated by Django 4.2.5 on 2023-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0002_telegramlinkcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramlinkcode",
            name="chat_id",
            field=models.BigIntegerField(),
        ),
    ]
