# Generated by Django 4.2.5 on 2023-09-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0003_alter_telegramlinkcode_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramlinkcode",
            name="chat_name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
