# Generated by Django 4.2.5 on 2023-09-06 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0005_alter_telegramlinkcode_chat_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramlinkcode",
            name="chat_name",
        ),
    ]
