# Generated by Django 4.2.5 on 2023-10-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0006_remove_telegramlinkcode_chat_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="monitor_type",
            field=models.CharField(
                choices=[
                    ("ping", "Ping (ICMP)"),
                    ("tcp", "TCP"),
                    ("tls", "TLS"),
                    ("imap", "IMAP"),
                    ("pop3", "POP3"),
                    ("smtp", "SMTP"),
                    ("http", "HTTP"),
                    ("ssh", "SSH"),
                ],
                max_length=32,
            ),
        ),
    ]
