# Generated by Django 4.2.5 on 2023-10-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0007_alter_monitor_monitor_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="alert_group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitoring.alertgroup",
            ),
            preserve_default=False,
        ),
    ]
